#!/usr/bin/env bash
set -euo pipefail

LOG_DIR=/var/log/phyt
LOGFILE=$LOG_DIR/remote-deploy.log
mkdir -p "$LOG_DIR"
chmod 755 "$LOG_DIR"
exec > >(tee -a "$LOGFILE") 2>&1

log() { printf "[REMOTE-DEPLOY] [%s] %s\n" "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "$*"; }
err() { printf "[REMOTE-DEPLOY] [%s] ERROR: %s\n" "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "$*" >&2; }
die() {
	err "$*"
	exit 1
}

req() { : "${!1:?Environment variable "$1" must be set}"; }

# Required environment variables
req IMAGE_REGISTRY
req GITHUB_REPOSITORY
req COMPOSE_PROFILES
req DEPLOYMENT_ID
req VAULT_ADDR
req VAULT_ROLE_ID
req VAULT_SECRET_ID
req VAULT_ENV

ROOT="/opt/phyt"
COMPOSE="docker compose"

export COMPOSE_PROFILES
export IMAGE_REGISTRY
export GITHUB_REPOSITORY
export DEPLOYMENT_ID
export VAULT_ADDR
export VAULT_ROLE_ID
export VAULT_SECRET_ID
export VAULT_ENV

ENV_FILE="${ROOT}/.env"
umask 077
cat >"${ENV_FILE}" <<EOF
# Auto-generated by remote-deploy.sh
# To get Docker to shut the fuck up about GITHUB_REPOSITORY
GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
IMAGE_REGISTRY=${IMAGE_REGISTRY}
COMPOSE_PROFILES=${COMPOSE_PROFILES}
VAULT_ADDR=${VAULT_ADDR}
VAULT_ENV=${VAULT_ENV}
DEPLOYMENT_ID=${SHORT_SHA}
EOF

log "======================================"
log "Starting remote-deploy script"
log "Working dir: ${ROOT}"
log "Profiles: ${COMPOSE_PROFILES}"
log "Deployment ID: ${DEPLOYMENT_ID}"
log "====================================="

[ -d "$ROOT" ] || die "Directory ${ROOT} not found"
cd "$ROOT"

command -v docker >/dev/null 2>&1 || die "docker not installed"
docker version >/dev/null 2>&1 || die "docker daemon not responding"

log "Rendering compose config…"
$COMPOSE config -o /tmp/compose.yml >/dev/null || die "Failed to render docker config"

log "Pulling images…"
$COMPOSE pull

log "Stopping existing services…"
$COMPOSE down --remove-orphans

log "Starting services…"
$COMPOSE up -d --remove-orphans

if [[ -n "${GHCR_TOKEN-}" ]]; then
	docker logout ghcr.io >/dev/null 2>&1 || true
fi

log "Deploy complete - services started"
log "Use 'docker compose ps' and 'docker compose logs <service>' to monitor health"
