pull_request_rules:
    - name: Close external PRs
      conditions:
          - author≠@PhytDotFun
          - -author~=^(dependabot|renovate|github-actions)\[bot\]$
      actions:
          close:
              message: 'Pull requests are limited to organization members.'
