[install]
# Let pnpm handle package management
auto = false
production = false
# Respect pnpm lockfile
lockfile = false

[install.cache]
# Disable Bun package cache
disable = true

[install.scopes]

[build]
minify = true
splitting = true
# Target modern Node.js for better performance
target = "node20"

[run]
# Enable faster hot reloading
hot = true
# Use better source maps for debugging
sourcemap = "inline"

[test]
# Use Bun's built-in test runner optimizations
coverage = false
# Faster test execution
bail = 1