services:
    hono-api:
        restart: always

    workers:
        restart: always

    postgres:
        restart: always

    redis:
        restart: always

    vault-agent:
        restart: always
