services:
    vault-agent:
        image: hashicorp/vault:latest
        container_name: vault-agent
        cap_add:
            - IPC_LOCK
        user: root
        security_opt:
            - no-new-privileges:true
        volumes:
            - ./tooling/vault:/vault/config:ro
            - ${CREDENTIALS_DIR:-./tooling/vault/credentials}:/vault/credentials:ro
            - ./tooling/vault/templates:/vault/templates:ro
            - vault-secrets:/vault/secrets # RW mount
        environment:
            - VAULT_ENV=${VAULT_ENV:-dev}
        entrypoint:
            ['/bin/sh', '-lc', '/vault/config/scripts/agent-entrypoint.sh']
        restart: unless-stopped

    hono-api:
        image: phyt/hono-api
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PROJECT: 'hono-api'
                NODE_ENV: 'production'
        container_name: hono-api
        depends_on:
            vault-agent:
                condition: service_started
            postgres:
                condition: service_healthy
            redis:
                condition: service_started
        volumes:
            - vault-secrets:/vault/secrets:ro # RO mount
            - ./tooling/ops/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
        entrypoint: ['/usr/local/bin/docker-entrypoint.sh']
        environment:
            - WAIT_FOR_SECRET_FILE=/vault/secrets/hono-api.env
        command: ['node', 'dist/index.js']
        restart: unless-stopped

    workers:
        image: phyt/workers
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PROJECT: 'workers'
                NODE_ENV: 'production'
        container_name: workers
        depends_on:
            vault-agent:
                condition: service_started
            postgres:
                condition: service_healthy
            redis:
                condition: service_started
        volumes:
            - vault-secrets:/vault/secrets:ro # RO mount
            - ./tooling/ops/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
        entrypoint: ['/usr/local/bin/docker-entrypoint.sh']
        environment:
            - WAIT_FOR_SECRET_FILE=/vault/secrets/workers.env
        command: ['node', 'dist/index.js']
        restart: unless-stopped

    postgres:
        image: postgres:17
        container_name: postgres
        depends_on:
            - vault-agent
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./tooling/ops/docker-entrypoint.sh:/usr/local/bin/wait-for-secrets.sh:ro
            - vault-secrets:/vault/secrets:ro

        entrypoint:
            [
                '/usr/local/bin/wait-for-secrets.sh',
                'docker-entrypoint.sh',
                'postgres'
            ]
        environment:
            - WAIT_FOR_SECRET_FILE=/vault/secrets/postgres.env
            - POSTGRES_INITDB_ARGS=--auth=scram-sha-256 --auth-host=scram-sha-256 --auth-local=scram-sha-256
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -q -h 127.0.0.1 -p 5432']
            interval: 3s
            timeout: 3s
            start_period: 30s
            retries: 20
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        container_name: redis
        restart: unless-stopped

    # Development Vite server for the web app
    vite:
        image: node:22-alpine
        working_dir: /repo/apps/web
        command: sh -lc "npm -v >/dev/null || true && pnpm -v >/dev/null || npm i -g pnpm && pnpm -w install && pnpm -w --filter @phyt/web dev --host"
        volumes:
            - ./:/repo
        ports:
            - '5173:5173'
        depends_on:
            - hono-api
        profiles: [dev]

    # Nginx reverse-proxy for dev, routing / to Vite and /api to Hono
    nginx:
        image: nginx:alpine
        volumes:
            - ./tooling/nginx/dev.nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - vite
            - hono-api
        ports:
            - '8080:8080'
        profiles: [dev]

    # Nginx for staging/prod-style serving of built SPA, proxies /api to Hono
    web:
        image: nginx:alpine
        volumes:
            - ./apps/web/dist:/usr/share/nginx/html:ro
            - ./tooling/nginx/staging.nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - hono-api
        ports:
            - '8080:8080'
        profiles: [staging]

volumes:
    vault-secrets:
    postgres-data:
