packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@changesets/cli': ^2.29.6
  '@commitlint/cli': 19.8.1
  '@commitlint/config-conventional': 19.8.1
  '@eslint/js': ^9.33.0
  '@hono/node-server': ^1.18.2
  '@hono/trpc-server': ^0.4.0
  '@hono/zod-validator': ^0.7.2
  '@hookform/resolvers': ^5.2.1
  '@next/eslint-plugin-next': ^15.4.6
  '@privy-io/react-auth': ^2.21.2
  '@privy-io/server-auth': ^1.31.0
  '@radix-ui/react-accordion': ^1.2.11
  '@radix-ui/react-alert-dialog': ^1.1.14
  '@radix-ui/react-aspect-ratio': ^1.1.7
  '@radix-ui/react-avatar': 1.1.10
  '@radix-ui/react-checkbox': ^1.3.2
  '@radix-ui/react-collapsible': ^1.1.11
  '@radix-ui/react-context-menu': ^2.2.15
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-dropdown-menu': ^2.1.15
  '@radix-ui/react-hover-card': ^1.1.14
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-menubar': ^1.1.15
  '@radix-ui/react-navigation-menu': ^1.2.13
  '@radix-ui/react-popover': ^1.1.14
  '@radix-ui/react-progress': ^1.1.7
  '@radix-ui/react-radio-group': ^1.3.7
  '@radix-ui/react-scroll-area': ^1.2.9
  '@radix-ui/react-select': ^2.2.5
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slider': ^1.3.5
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': ^1.2.5
  '@radix-ui/react-tabs': ^1.1.12
  '@radix-ui/react-toggle': ^1.1.9
  '@radix-ui/react-toggle-group': ^1.1.10
  '@radix-ui/react-tooltip': ^1.2.7
  '@t3-oss/env-core': ^0.13.8
  '@tailwindcss/vite': ^4.1.11
  '@tanstack/eslint-config': ^0.3.0
  '@tanstack/react-query': ^5.85.0
  '@tanstack/react-router': ^1.121.40
  '@tanstack/react-router-devtools': ^1.131.7
  '@tanstack/router-plugin': ^1.131.7
  '@testing-library/dom': ^10.4.1
  '@testing-library/react': ^16.3.0
  '@trpc/client': ^11.4.4
  '@trpc/server': ^11.4.4
  '@trpc/tanstack-react-query': ^11.4.4
  '@turbo/gen': ^2.5.5
  '@types/hashids': ^2.0.1
  '@types/node': ^24.2.1
  '@types/pg': ^8.15.5
  '@types/react': ^19.1.10
  '@types/react-dom': ^19.1.7
  '@vitejs/plugin-react': ^5.0.0
  babel-plugin-react-compiler: 19.1.0-rc.2
  bullmq: 5.56.9
  chalk: 5.6.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  concurrently: ^9.2.0
  crypto: 1.0.1
  date-fns: ^4.1.0
  dotenv: 17.2.1
  dotenv-cli: ^10.0.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.4
  drizzle-zod: ^0.8.3
  embla-carousel-react: ^8.6.0
  esbuild: ^0.24.2
  eslint: ^9.33.0
  eslint-config-prettier: ^10.1.8
  eslint-import-resolver-typescript: ^4.4.4
  eslint-plugin-import: ^2.32.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-hooks: 6.0.0-rc1
  eslint-plugin-turbo: ^2.5.5
  globals: ^16.3.0
  hashids: ^2.3.0
  hono: ^4.9.1
  husky: ^9.1.7
  input-otp: ^1.4.2
  ioredis: 5.7.0
  jsdom: ^26.1.0
  lint-staged: ^16.1.5
  lucide-react: ^0.539.0
  next-themes: ^0.4.6
  pg: ^8.16.3
  pino: ^9.8.0
  prettier: ^3.6.2
  react: ^19.1.1
  react-day-picker: ^9.8.1
  react-dom: ^19.1.1
  react-hook-form: ^7.62.0
  react-resizable-panels: ^3.0.4
  recharts: ^2.15.4
  rimraf: ^6.0.1
  sonner: ^2.0.7
  superjson: ^2.2.2
  svix: ^1.71.0
  syncpack: 14.0.0-alpha.19
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  tsup: ^8.5.0
  tsx: 4.20.3
  turbo: ^2.5.4
  tw-animate-css: ^1.3.6
  typescript: ^5.9.2
  typescript-eslint: ^8.39.1
  vaul: ^1.1.2
  viem: ^2.33.3
  vite: ^7.1.2
  vitest: ^3.2.4
  web-vitals: ^4.2.4
  zod: 4.0.17

catalogMode: prefer

onlyBuiltDependencies:
  - '@reown/appkit'
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - secp256k1
  - unrs-resolver
  - utf-8-validate
