version: '3'

tasks:
    build:
        desc: Build the core package
        cmds:
            - pnpm build

    dev:
        desc: Start development mode for core package
        cmds:
            - pnpm dev

    test:
        desc: Run tests for core package
        cmds:
            - pnpm test

    lint:
        desc: Lint the core package
        cmds:
            - pnpm lint

    clean:
        desc: Clean build artifacts
        cmds:
            - pnpm clean
