[profile.ci]
fuzz = { runs = 10_000 }

[profile.default]
libs = ["dependencies"]
test = "test"
src = "src"
out = "out"
gas_reports = ["*"]

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.0.2"
