version: '3'

tasks:
    build:
        desc: Build Hono API application
        cmds:
            - pnpm build

    dev:
        desc: Start Hono API development server
        cmds:
            - pnpm dev

    start:
        desc: Start Hono API production server
        cmds:
            - pnpm start

    lint:
        desc: Lint Hono API application
        cmds:
            - pnpm lint

    type-check:
        desc: Run TypeScript type checking
        cmds:
            - pnpm type-check

    test:
        desc: Run Hono API tests
        cmds:
            - pnpm test
