name: Release Images
on:
    push:
        tags:
            - 'v*'
jobs:
    build_and_push_release_images:
        runs-on: ubuntu-latest
        env:
            REGISTRY: ghcr.io
            IMAGE_PREFIX: ${{ github.repository }}
            VERSION: ${{ github.ref_name }}
        steps:
            - uses: actions/checkout@v4
            - uses: docker/setup-buildx-action@v3
            - uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - uses: docker/metadata-action@v5
              id: meta-hono-api
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/hono-api
                  tags: |
                      type=raw,value=${{ env.VERSION }}
                      type=raw,value=latest
            - uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: ${{ steps.meta-hono-api.outputs.tags }}
                  labels: ${{ steps.meta-hono-api.outputs.labels }}
                  build-args: PROJECT=hono-api
            - uses: docker/metadata-action@v5
              id: meta-workers
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/workers
                  tags: |
                      type=raw,value=${{ env.VERSION }}
                      type=raw,value=latest
            - uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: ${{ steps.meta-workers.outputs.tags }}
                  labels: ${{ steps.meta-workers.outputs.labels }}
                  build-args: PROJECT=workers
